uvicorn:
  host: "127.0.0.1"
  port: 8007

trees:
  - path: /
    tree: catalog
    args:
      uri: "sqlite:///catalog.db"
      init_if_not_exists: true
      writable_storage: "storage"
      adapters_by_mimetype:
        application/x-zarr: sfx_zarr_adapter:SFXZarrAdapter
      readable_storage:
        - /lustre/orion/lrn091/proj-shared/data
